CREATE TABLE [dbo].[tblOrder]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[CustomerID] INT NOT NULL,
	[OrderDate] DATETIME NOT NULL,
	[UserID] INT NOT NULL,
	[ShipDate] DATETIME,
	CONSTRAINT [FK_OrderCustomerID] FOREIGN KEY (CustomerID) REFERENCES tblCustomer(ID),
	CONSTRAINT [FK_OrderUserID] FOREIGN KEY (UserID) REFERENCES tblUser(ID)
)
